In [13]:
print?
'''
Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method
'''

In [2]:
a = [1,2,3]
a?

In [3]:
def add_numbers(a, b):
    """
    Add two numbers together

    Returns
    -------
    the_sum : type of arguments
    """
    return a + b

In [4]:
add_numbers?

In [5]:
import numpy as np

np.*load*?  # give you all methods in numpy that start with load

In [7]:
import pandas as pd 

pd.*read*?  

'''
pd.read_clipboard
pd.read_csv
pd.read_excel
pd.read_feather
pd.read_fwf
pd.read_gbq
pd.read_hdf
pd.read_html
pd.read_json
pd.read_orc
pd.read_parquet
pd.read_pickle
pd.read_sas
pd.read_spss
pd.read_sql
pd.read_sql_query
pd.read_sql_table
pd.read_stata
pd.read_table
pd.read_xml

'''

In [8]:
# Define more than one variable in the same line
a = 5; b = 6; c = 7

b,c,a

(6, 7, 5)

In [9]:
c,a,b

(7, 5, 6)

In [10]:
b

6

In [18]:
def append_only_numbers(some_list, element):
        if type(element) == int or type(element) == float:
            some_list.append(element)
        else:
            print('This method append only numeric data')

In [19]:
 data = [1, 2, 3]

append_only_numbers(data,5)

In [20]:
data

[1, 2, 3, 5]

In [21]:
append_only_numbers(data,"fgd")

This method append only numeric data


In [22]:
# isinstance can accept a tuple of types 

a = 5; b = 4.5

isinstance(a, (int, float))

True

In [24]:
isinstance(b, (int, str))

False

In [34]:
name = 'my name is ibrahim'

getattr(name, "split")

<function str.split(sep=None, maxsplit=-1)>

In [29]:
# check if the variable has the attribute
hasattr(name,'upper')

True

In [30]:
hasattr(name,'isdigit')

True

In [31]:
hasattr(name,'take')

False

In [37]:
# The setattr() function sets the value of the attribute of an object.

class Student:
    marks = 88
    name = 'ibrahim'

person = Student()

# set value of name to Adam
setattr(person, 'name', 'Adam')

person.name

'Adam'

In [38]:
# set value of marks to 78
setattr(person, 'marks', 78)
print(person.marks)

78


In [3]:
def isiterable(obj):
    try:
            iter(obj) # verify that an object is iterable
            return True
    except TypeError: # not iterable
            return False

In [4]:
isiterable("a string")

True

In [5]:
isiterable([1, 2, 3])

True

In [6]:
isiterable(15)

False

In [7]:
# EXCLUSIVE-OR

a = True
b = False
a ^ b

True

In [8]:
b ^ a # True if a or b is True, but not both

True

In [9]:
True ^ True

False

In [10]:
a = [1, 2, 3]

b = a

c = list(a)

a is b # True if a and b reference the same Python object

True

In [11]:
a is not c # True if a and c reference different Python objects

True

In [16]:
a , c

([1, 2, 3], [1, 2, 3])

In [12]:
a == c # a,c have the same content

True

In [13]:
a is c

False

In [14]:
id(a) , id(c)

(2393280321856, 2393281866496)

In [15]:
id(a) == id(c) # have differnt ids

False

# Scalar Types

None -->	The Python “null” value (only one instance of the None object exists)

str -->	    String type; holds Unicode strings

bytes -->	Raw binary data

float -->	Double-precision floating-point number (note there is no separate double type)

bool -->	A Boolean True or False value

int	-->    Arbitrary precision integer

In [17]:
notation = 6.78e-5
notation

6.78e-05

In [18]:
notation * 10**5

6.779999999999999

In [19]:
c = """
This is a longer string that
spans multiple lines
"""

c.count('\n') # We can count the new line characters.

3

In [20]:
# string with alot of backslashes

s = r"this\has\no\special\characters"
s

'this\\has\\no\\special\\characters'

In [22]:
template = "{0:.2f} {1:s} are worth US${2:d}"
template.format(88.46, "Argentine Pesos", 1) 

'''
{0:.2f} means to format the first argument as a floating-point number with two decimal places.

{1:s} means to format the second argument as a string.

{2:d} means to format the third argument as an exact integer.

'''

'88.46 Argentine Pesos are worth US$1'

In [23]:
# A New Formatting
amount = 10

rate = 88.46

currency = "Pesos"

result = f"{amount} {currency} is worth US${amount / rate}"

result

'10 Pesos is worth US$0.11304544426859599'

In [24]:
result = f"{amount} {currency} is worth US${amount / rate:.2f}"
result

'10 Pesos is worth US$0.11'

In [25]:
# Bytes and Unicode

val = "español"
val_utf8 = val.encode("utf-8")

val_utf8

b'espa\xc3\xb1ol'

In [26]:
type(val_utf8)

bytes

In [27]:
val_utf8.decode("utf-8")

'español'

In [28]:
decoded_val = val_utf8.decode("utf-8")

decoded_val

'español'

In [29]:
type(decoded_val)

str

In [30]:
val_utf16 = val.encode("utf-16")

val_utf16

b'\xff\xfee\x00s\x00p\x00a\x00\xf1\x00o\x00l\x00'

In [31]:
val_latin1 = val.encode("latin1")

val_latin1

b'espa\xf1ol'

In [32]:
val_latin1.decode("latin1")

'español'

In [1]:
from datetime import datetime, date, time

dt = datetime(2011, 10, 29, 20, 30, 21)

dt

datetime.datetime(2011, 10, 29, 20, 30, 21)

In [34]:
dt.day

29

In [35]:
dt.hour

20

In [36]:
dt.month

10

In [37]:
dt.date()

datetime.date(2011, 10, 29)

In [38]:
dt.time()

datetime.time(20, 30, 21)

In [39]:
# The strftime method formats a datetime as a string
dt.strftime("%Y-%m-%d %H:%M")

'2011-10-29 20:30'

In [2]:
dt2 = datetime(2011, 11, 15, 22, 30)
delta = dt2 - dt

delta

datetime.timedelta(days=17, seconds=7179)

In [3]:
dt + delta

datetime.datetime(2011, 11, 15, 22, 30)

In [4]:
sequence = [1, 2, None, 4, None, 5]
total = 0
for value in sequence:
    if value is None:
        continue
    total += value
    
print(total)    

12


In [1]:
# If an object inside a tuple is mutable, such as a list, you can modify it in place:

tup = tuple(['foo', [1, 2], True])
tup[1].append(5)

tup

('foo', [1, 2, 5], True)

In [2]:
# You can concatenate tuples using the + operator to produce longer tuples .

(4, None, 'foo') + (6, 0) + ('bar',)

(4, None, 'foo', 6, 0, 'bar')

In [3]:
# Unpacking tuples
tup = (4, 5, 6)

a, b, c = tup

b

5

In [4]:
a + c

10

In [5]:
# A common use of variable unpacking is iterating over sequences of tuples or lists:

seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

for a, b, c in seq:
     print(f'a={a}, b={b}, c={c}')

a=1, b=2, c=3
a=4, b=5, c=6
a=7, b=8, c=9


In [6]:
values = 1, 2, 3, 4, 5

a, b, *rest = values

rest

[3, 4, 5]

In [7]:
a_list = [1,5,3,4,7]

a_list.insert(8,6)

In [8]:
a_list # if the index greater than the len , it stores the object in the last index

[1, 5, 3, 4, 7, 6]

In [9]:
# Similar to tuples, adding two lists together with + concatenates them

[4, None, "foo"] + [7, 8, (2, 3)]

[4, None, 'foo', 7, 8, (2, 3)]

In [15]:
# better performance 

list_1 = [4, None, "foo"] 
list_2 = [7, 8, (2, 3)]

list_1.extend(list_2)

list_1

[4, None, 'foo', 7, 8, (2, 3)]

In [17]:
# sort by length
b = ["saw", "small", "He", "foxes", "six"]
    
b.sort(key=len)    

b

['He', 'saw', 'six', 'small', 'foxes']

In [18]:
# sort by length - Descending
b = ["saw", "small", "He", "foxes", "six"]
    
b.sort(key=len,reverse= True)    

b

['small', 'foxes', 'saw', 'six', 'He']

In [19]:
d1 = {'a': 'some value',
 'b': [1, 2, 3, 4],
 7: 'an integer',
 'dummy': 'another value'}

d1.pop('dummy') # return the value for dummy and remove key, value from the dictionary

'another value'

In [20]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [21]:
# merge one dictionary into another using the update method

d1.update({"b": "foo", "c": 12})

d1

{'a': 'some value', 'b': 'foo', 7: 'an integer', 'c': 12}

In [22]:
tuples = zip(range(5), reversed(range(5)))

tuples

In [23]:
mapping = dict(tuples)
mapping

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

In [1]:
words = ["apple", "bat", "cat", "bar", "atom", "book"]

by_letter = {}

for word in words:
    letter = word[0]
    by_letter.setdefault(letter, []).append(word)
    
by_letter    

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book'], 'c': ['cat']}

In [2]:
from collections import defaultdict

by_letter_collections = defaultdict(list)


for word in words:
    by_letter_collections[word[0]].append(word)
    
by_letter_collections    

defaultdict(list,
            {'a': ['apple', 'atom'],
             'b': ['bat', 'bar', 'book'],
             'c': ['cat']})

In [3]:
hash('name')

-848092377465333270

In [4]:
hash(15)

15

In [9]:
# hash([1,2,(3,4,5)]) -> unhashable type: 'list'

hash((1,2,(3,4,5)))

2941677136697153642

In [10]:
my_data = [1, 2, 3, 4]

my_set = {tuple(my_data)}

my_set

{(1, 2, 3, 4)}

In [11]:
# Sets are equal if and only if their contents are equal:

{1, 2, 3} == {3, 2, 1}

True

# List, Set, and Dictionary Comprehensions

In [12]:
strings = ["a", "as", "bat", "car", "dove", "python"]

# covert strings to upper if length > 2
[x.upper() for x in strings if len(x) > 2]

['BAT', 'CAR', 'DOVE', 'PYTHON']

In [13]:
# Suppose we wanted a set containing just the lengths of the strings contained in the collection

unique_lengths = {len(x) for x in strings}
unique_lengths

{1, 2, 3, 4, 6}

In [14]:
# We could also express this more functionally using the map function, introduced shortly

set(map(len,strings))

{1, 2, 3, 4, 6}

In [15]:
# by dictionary comprehension
loc_mapping = {value: index for index, value in enumerate(strings)}
loc_mapping

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

In [16]:
# Nested list comprehensions

all_data = [["John", "Emily", "Michael", "Mary", "Steven"],
            ["Maria", "Juan", "Javier", "Natalia", "Pilar"]]

# Suppose we wanted to get a single list containing all names with two or more a’s in them.

result = [name for names in all_data for name in names if name.count("a") >= 2]

result

['Maria', 'Natalia']

In [17]:
# flatten a list of tuples of integers into a simple list of integers

some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
flattened = [x for tup in some_tuples for x in tup]

flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
# This produces a list of lists, rather than a flattened list of all of the inner elements.

list_of_lists = [[x for x in tup] for tup in some_tuples]

list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
a = None

def bind_a_variable():
    global a
    a = []
bind_a_variable()
    

print(a)

[]


In [20]:
a = None

def bind_a_variable():
    a = []
bind_a_variable()
    

print(a)

None


In [21]:
import re

def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub("[!#?]", "", value)
        value = value.title()
        result.append(value)
    return result

states = ["   Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda","south   carolina##", "West virginia?"]

clean_states = clean_strings(states)

clean_states

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [23]:
# make a list of the operations you want to apply to a particular set of strings.

def remove_punctuation(value):
    return re.sub("[!#?]", "", value)

clean_ops = [str.strip, remove_punctuation, str.title] # string methods

def clean_strings(strings, ops):
    result = []
    for value in strings:
        for func in ops:
            value = func(value)
        result.append(value)
    return result

clean_states = clean_strings(states,clean_ops)

clean_states

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [24]:
# Using map and remove_punctuation functions
for x in map(remove_punctuation, states):
     print(x)

   Alabama 
Georgia
Georgia
georgia
FlOrIda
south   carolina
West virginia


In [25]:
for x in map(remove_punctuation, states):
     print(x.strip().title())

Alabama
Georgia
Georgia
Georgia
Florida
South   Carolina
West Virginia


In [28]:
# apply labmda and normal functions in the same code
def apply_to_list(some_list, f):
    return [f(x) for x in some_list]

integers = [4, 0, 1, 5, 6]

apply_to_list(integers, lambda x: x ** 2)

[16, 0, 1, 25, 36]

In [30]:
# suppose you wanted to sort a collection of strings by the number of distinct letters in each string.
strings = ["foo", "card", "bar", "aaaa", "abab"]
strings.sort(key=lambda x: len(set(x)))

strings

['aaaa', 'foo', 'abab', 'bar', 'card']

In [31]:
#  generators can return a sequence of multiple values by pausing and resuming execution each time the generator is used.
def squares(n=10):
    print(f"Generating squares from 1 to {n ** 2}")
    for i in range(1, n + 1):
        yield i ** 2
        
gen = squares()
gen        

<generator object squares at 0x0000020AF57F7CF0>

In [32]:
list(gen)

Generating squares from 1 to 100


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [33]:
[*gen] # 

[]

In [34]:
gen = squares()
[*gen]

Generating squares from 1 to 100


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [37]:
#  generator expression: This is a generator analogue to list, dictionary, and set comprehensions. 
gen = (x for x in range(0,100,5))

list(gen)

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [38]:
sum(x for x in range(100))

4950

In [39]:
# Generator expressions can be used instead of list comprehensions as function arguments in some cases:
dict((i, i ** 2) for i in range(5))

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [40]:
# The standard library itertools module has a collection of generators for many common data algorithms. 
# For example, groupby takes any sequence and a function,
# grouping consecutive elements in the sequence by return value of the function.

import itertools

def first_letter(x):
    return x[0]

names = ["Alan", "Adam", "Wes", "Will", "Albert", "Steven"]
for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names)) # names is a generator

A ['Alan', 'Adam']
W ['Wes', 'Will']
A ['Albert']
S ['Steven']


In [41]:
names = ['Ibrahim','Ali','Ahmed','Mona','Rana','Ramy','Islam']

for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names)) # names is a generator

I ['Ibrahim']
A ['Ali', 'Ahmed']
M ['Mona']
R ['Rana', 'Ramy']
I ['Islam']


In [42]:
names = ['Islam','Ibrahim','Ali','Ahmed','Mona','Rana','Ramy']

for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names)) # names is a generator

I ['Islam', 'Ibrahim']
A ['Ali', 'Ahmed']
M ['Mona']
R ['Rana', 'Ramy']


In [44]:
def attempt_float(x):
    try:
        return float(x)
    except:
        return x , " --> can't convert to float" 
    
attempt_float("15.34")    

15.34

In [45]:
attempt_float("my name is Ibrahim Zaitoun")

('my name is Ibrahim Zaitoun', " --> can't convert to float")

In [46]:
# catch multiple exception types by writing a tuple of exception types
def attempt_float(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return x
    
attempt_float("my name is Ibrahim Zaitoun")    

'my name is Ibrahim Zaitoun'

In [47]:
attempt_float([1,2,3])

[1, 2, 3]

In [48]:
attempt_float((1,2,3))

(1, 2, 3)

In [49]:
%run efficient_code.ipynb # run another notebook in the same directory and print the outputs.

<class 'range'>
[0, 1, 2, 3, 4]
[1, 3, 5, 7, 9]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']
['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']
<class 'map'>
['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']
[3, 23, 12, 20, 12, 14, 79]
[2 4 8 5 7]
int32
[2.25 4.   8.   5.6  7.  ]
float64
[ 6 12 24 15 21]
2
[[1 2 3]
 [4 5 6]]
2
[2 5]
[1 2 3]
[2 4 8 5 7]
[False  True  True  True  True]
[4 8 5 7]
[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]
Welcome to Festivus Jerry... You're 7 min late.
Welcome to Festivus Kramer... You're 17 min late.
Welcome to Festivus Elaine... You're 27 min lat

D:\anaconda\lib\site-packages\memory_profiler.py:735: UserWarning: Could not extract a code object for the object <built-in function arange>
  warnings.warn("Could not extract a code object for the object %r"


In [52]:
my_file = open('document.txt','x',encoding= 'utf-8')

In [53]:
my_file.write("""
This notebook contains python tips from a famous book
the book called python for data analysis
the book have 15 chapters and help you to understand python from basics to be hero
""")

179

In [54]:
my_file.close()

In [60]:
with open('document.txt') as f:
    print("Cursor at :",f.tell())  # tell gives you the current position
    lines = [x.rstrip() for x in f]
    print("Cursor at :",f.tell())

Cursor at : 0
Cursor at : 183


In [61]:
lines

['',
 'This notebook contains python tips from a famous book',
 'the book called python for data analysis',
 'the book have 15 chapters and help you to understand python from basics to be hero']

In [62]:
import sys
sys.getdefaultencoding() # the default encoding

'utf-8'

In [64]:
f.closed # True if the file is closed

True